[versions]

# SDK and tooling versions - Used in buildLogic plugins.
# Android Studio can't tell that so it thinks they're unused
compileSdk = "35"
buildToolsVersion = "35.0.0"

androidGradlePlugin = "8.2.2"
designcompose = "0.30.0"
mockito = "2.28.4"
kotlin = "1.9.21"
ksp = "1.9.21-1.0.16"
protobuf = "4.27.2"
protobufGradlePlugin = "0.9.4"
robolectric = "4.12"

[libraries]
designcompose = { module = "com.android.designcompose:designcompose", version.ref = "designcompose" }
designcompose-codegen = { module = "com.android.designcompose:codegen", version.ref = "designcompose" }

dexmaker-mockito-inline = { module = "com.linkedin.dexmaker:dexmaker-mockito-inline", version.ref = "mockito" }
dexmaker-mockito-inline-extended = { module = "com.linkedin.dexmaker:dexmaker-mockito-inline-extended", version.ref = "mockito" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
designcompose = { id = "com.android.designcompose", version.ref = "designcompose" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufGradlePlugin" }
