# Documentation: https://developer.android.com/build/migrate-to-catalogs
# Naming convention inspired by https://github.com/android/nowinandroid/blob/main/gradle/libs.versions.toml
# Keep Sorted: https://github.com/google/keep-sorted?tab=readme-ov-file#sorting-your-file

[versions]
# go/keep-sorted start
junit4 = "4.13.2"
# go/keep-sorted end

### Core Build System - Update with care
# go/keep-sorted start
aaosLatestSDK = "33"
aaosPlatformSDKVersion = "33" # Change this to the most recent android API level.
aaosTargetSDK = "33"
androidGradlePlugin = "7.4.2"
kotlin = "1.8.22"
# go/keep-sorted end

[libraries]
# go/keep-sorted start
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
# go/keep-sorted end

[plugins]
# go/keep-sorted start
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
# go/keep-sorted end
